"""Adding host field to cabinet

Revision ID: 0e234e933de4
Revises: 1905820624ad
Create Date: 2023-11-26 15:55:50.843777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e234e933de4'
down_revision = '1905820624ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cabinets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host', sa.String(length=1000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cabinets', schema=None) as batch_op:
        batch_op.drop_column('host')

    # ### end Alembic commands ###
