"""Adding components

Revision ID: c2df0024354b
Revises: f24d759b7f74
Create Date: 2023-11-25 16:13:38.232043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2df0024354b'
down_revision = 'f24d759b7f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compartments', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawers', schema=None) as batch_op:
        batch_op.drop_column('compartments')

    # ### end Alembic commands ###
